# Generated by Django 5.0.3 on 2024-03-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='host',
            field=models.ForeignKey(limit_choices_to={'is_host': True}, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='users.user'),
        ),
    ]
