# Generated by Django 5.0.3 on 2024-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='check_in_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='check_in_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='checkout_instructions',
            field=models.ManyToManyField(blank=True, null=True, to='destinations.checkoutinstruction'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='property_information',
            field=models.ManyToManyField(blank=True, null=True, to='destinations.propertyinformation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='safety_considerations',
            field=models.ManyToManyField(blank=True, null=True, to='destinations.safetyconsideration'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='safety_devices',
            field=models.ManyToManyField(blank=True, null=True, to='destinations.safetydevice'),
        ),
    ]
