# Generated by Django 5.0.3 on 2024-03-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_amenity_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='daily_price',
            new_name='nightly_price',
        ),
    ]
