# Generated by Django 5.0.3 on 2024-03-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookings', '0001_initial'),
        ('destinations', '0002_alter_destination_host'),
        ('users', '0002_alter_user_currency_alter_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
