# Generated by Django 5.0.3 on 2024-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookings', '0001_initial'),
        ('destinations', '0002_alter_destination_host'),
        ('users', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
